import "@/styles/globals.css"
import { Inter } from 'next/font/google';
import * as React from "react"
import type { Metadata, Viewport } from "next"
import { env } from "@/env.mjs"
import { ThemeProvider } from "@/providers/theme-provider"
import { Toaster } from "@/components/ui/toaster"
import { TailwindIndicator } from "@/components/tailwind-indicator"
import ScrollLayout from "@/components/layout/scroll-layout"
import { SmoothScrollProvider } from "@/providers/smooth-scroll-provider"


const inter = Inter({ subsets: ['latin'] });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: "/favicon.ico",
  },
};

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body>
        <ScrollLayout>
          <SmoothScrollProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="white"
                enableSystem
                disableTransitionOnChange
              >
              <div className={inter.className}>{children}</div>
              <Toaster />
              <TailwindIndicator />
            </ThemeProvider>
          </SmoothScrollProvider>
        </ScrollLayout>
      </body>
    </html>
  );
}
